repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.14.0
      hooks:
          - id: ruff-check
            args: [--select, F401, --select, I, --fix]
          - id: ruff-format
            args: [--config, pyproject.toml]

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.3
      hooks:
          - id: prettier
            exclude: '\.md$'
            args: [--config, .prettierrc]
